### ISSUE TITLE
Key Use Cases

### ISSUE THREAD

**Issue by alexfigtree** [alexfigtree/CoreID#18]

**Comment by dazzaji** [comment]
I've made an initial update of the [Key Uses Cases](https://github.com/alexfigtree/CoreID/blob/master/docs/Key_Use_Cases.md) file (here), renaming the use cases to:
* [Identity Verification](https://github.com/alexfigtree/CoreID/blob/master/docs/Key_Use_Cases.md#identity-verification-use-case) Use Case, and 
* [Mortgage Application](https://github.com/alexfigtree/CoreID/blob/master/docs/Key_Use_Cases.md#mortgage-application-use-case) Use Case

I'm thinking the [Identity Verification](https://github.com/alexfigtree/CoreID/blob/master/docs/Key_Use_Cases.md#identity-verification-use-case) Use Case should focus on the use of "verified claims" relating to identity attributes, such as the age, address, name, public key, etc of the Principal. The  [Mortgage Application](https://github.com/alexfigtree/CoreID/blob/master/docs/Key_Use_Cases.md#mortgage-application-use-case) Use Case should focus on the "document signature" prototype capability applied to data (whether in the form of plain text or a binary file) representing a ["Promissory Note"](https://en.wikipedia.org/wiki/Promissory_note#United_States_law) of [this type](https://github.com/jwalsh/profile-dns/wiki/Promissory-Note).

**Comment by dazzaji** [comment]
Got them here: https://github.com/mitmedialab/CoreID/blob/master/CreditUnionUseCase.md
