### ISSUE TITLE
Add scaffolding for Dashboard, Document, Claims

### ISSUE THREAD

**Issue by jwalsh** [alexfigtree/CoreID#2]

**Comment by alexfigtree** [comment]
@jwalsh Can you clarify what 'claims' are?  Currently, a user can choose from the following on the sidebar: (Identity) Attributes, Documents, Signatures, and Transactions. Please let me know if this needs to be modified.

**Comment by dazzaji** [comment]
I'll jump in for @jwalsh on this one.  "Claims" are synonymous with "attributes" or "certifications of fact" and sometimes called "verified claims".  They will convey information about or from a Member such as that the Member is "over 21 years old" or has a "preferred ship to address of 123 Elm Street, USA" and they are in the form of little JSON blurbs.
