### ISSUE TITLE
Express server to add CORS header

### ISSUE THREAD

**Issue by akscanb** [alexfigtree/CoreID#38]
I added an express server to see if I could deal with proxying all requests through it and add cors headers, but it seems it doesn't work as intended. You can try it yourself by running node server from the main CoreID directory.

**Comment by jwalsh** [comment]
@akscanb Will check but you might want to just bypass the issue by using NGINX in front of both bitcoind and the React application.  This would be something like the following in nginx.conf and viewing the application at http://localhost:8080/ : 

location /bitcoind {
    proxy_pass http://localhost:3885/;
}
location / {
    proxy_pass http://localhost:3000/;
}

**Comment by akscanb** [comment]
Works!

**Comment by dazzaji** [comment]
Can you remind which issue number that was? 

---
Sent from my iPhone

  Daniel "Dazza" Greenwood
  law.MIT.edu & CIVICS.com
  Email: dazza@civics.com
  Mobile: +1 617-500-3644
