### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by alexfigtree** [alexfigtree/CoreID#40]
The nginx configuration steps could use some modification. Modifying nginx.conf in etc/nginx did not work with the specified addresses. Using others seemed to help, but I am running into what are possibly unrelated issues involving jsonfile, index.js, webpack, etc.. Need to fish around some more, but it would be helpful if I could get a walkthrough of the nginx.conf setup just to be sure that it was configured properly.

**Comment by akscanb** [comment]
Can I see the current nginx configuration?

**Comment by alexfigtree** [comment]
This is my current nginx.conf, under `/usr/local/etc/nginx:`

```
events {
    worker_connections  1024;
}

http{

server {
    listen 8080;
    server_name localhost;

    location /bitcoind/ {
    proxy_pass http://localhost:8332/;

    }


    location / {
    proxy_pass http://localhost:3000/;
    }
  }
}


```

**Comment by akscanb** [comment]
Did you save the original config? Try adding the server config in to the original config. Also, if you have port 8080 occupied by a different app. You will need to change it to  a different port. Realize if you do this then you also need to modify where the client connects also.

**Comment by alexfigtree** [comment]
As soon as I posted my nginx configuration I realized all that it was missing. : ) Problem is no longer this nginx configuration (it has been fixed), but all the errors I've encountered after successfully running React instead. 

I've noticed many small changes made to the code that have caused errors on my inspector.  In particular for this commit, https://github.com/alexfigtree/CoreID/commit/82eeac7ac9b2b641e7dd424168be8db63819d880#diff-14b1e33d5bf5649597cdc0e4f684dadd, I noticed many 'imports' were modified, and this has resulting in poor navigation to individual claim and document sections, amongst other pages. 

Was there are reason for changing this, and have you (or anyone) encountered navigation problems on your end as a result?

**Comment by akscanb** [comment]
Interesting, there might have been some artifacts as I was quickly testing some stuff, and a result of me merging in the wrong stuff before pushing. That is my bad. However, I don't think that should cause major navigation problems as long as the routes stayed the same.

**Comment by alexfigtree** [comment]
Some of the routing was modified, but that's ok, I'll revert the changes since I will be working on documentation this weekend. If I have any other questions on your recent commits, I will create a separate issue.  Will close this one for now, thanks!
