### ISSUE TITLE
Create Initial Mockups

### ISSUE THREAD

**Issue by dazzaji** [alexfigtree/CoreID#5]
Mockups for Attestations, Documents, Signatures, and Transactions
* Added simple table to identity, advance and complete each mockup [here](https://github.com/alexfigtree/CoreID/blob/master/README.md#a-initial-mockups).

**Comment by dazzaji** [comment]
Not sure what "transactions" refers to but I think I like it!  @alexfigtree  what do you have in mind for this?

**Comment by alexfigtree** [comment]
@dazzaji  'Transactions' was the term used to refer to a series of actions between two parties, and that can encompass documents and signatures for a specific transaction.

**Comment by dazzaji** [comment]
Can you describe what this might link to?  Would it be a list of past
transactions?  Or maybe some kind of transactional system to conduct
transactions?  Or some sort of transaction designer to compose transactions
you want to conduct (eg listing the people that need to sign a document in
the order they need to sign it and perhaps some key terms like Alice must
sign before Bob, etc?  Something else?

**Comment by alexfigtree** [comment]
This could be three distinct subsections in the Transactions section of the dashboard, with 'current' or 'in process' transactions set to show by default when a user directs to the Transactions section using the sidebar. Other subsections would be 'completed', or 'create a transaction'. The 'create a transaction' subsection would implement the transaction designer you're speaking of. Please see https://github.com/alexfigtree/CoreID/blob/master/docs/Updated_mockup_5_27_17.png for what this would look like on the sidebar.
